# custom nodejs with express & vue-cli preinstalled
FROM node:8.9.1
RUN mkdir -p /src
# a volume to connect to host disk
VOLUME /src
# install dependencies in the docker?
#RUN npm install
EXPOSE 8080/tcp 3000/tcp

# start frontend
#WORKDIR /src/front
#CMD ["npm","start"]
